input_path: ../data_process/example_input.jsonl
output_path: results/SkyworkQwenScorer/
num_gpu: 4
num_gpu_per_job: 1
resume: true
scorers:
- name: SkyworkQwenScorer
  model: Skywork/Skywork-Reward-V2-Qwen3-8B
  batch_size: 8
  max_length: 1024
  num_gpu_per_job: 1
